import HeadComponet from "@/Components/HeadComponet"
import Link from "next/link"

const Privacy = () => {
  return (
    <>
        <HeadComponet title={'Privacy Policy'}/>
        <div className="container py-5">
            <h2 className="text-center pb-3">Privacy Policy</h2>
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            <div>
                <h4>Interpretation</h4>
                <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            </div>
            <div>
                <h4>Definitions</h4>
                <p>For the purposes of this Privacy Policy:</p>
                <p><span className="fw-bold">Account</span> means a unique account created for You to access our Service or parts of our Service.</p>
                <p><span className="fw-bold">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to E-Commerce, Rampur, Uttarpradesh.</p>
                <p><span className="fw-bold">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                <p><span className="fw-bold">Country</span> refers to: Uttar Pradesh, India</p>
                <p><span className="fw-bold">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                <p><span className="fw-bold">Personal</span> Data is any information that relates to an identified or identifiable individual.</p>
                <p><span className="fw-bold">Service</span> refers to the Website.</p>
                <p><span className="fw-bold">Service</span> Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                <p><span className="fw-bold">Third-party Social Media Service</span> refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
                <p><span className="fw-bold">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                <p><span className="fw-bold">Website</span> refers to E-Commerce, accessible from <Link href={'/'}>http://E-Commerce.com</Link></p>
                <p><span className="fw-bold">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
            </div>
            <div>
                <h4>Personal Data</h4>
                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <p>Email address</p>
                <p>First name and last name</p>
                <p>Phone number</p>
                <p>Address, State, Province, ZIP/Postal code, City</p>
                <p>Usage Data</p>
            </div>
            <div>
                <h4>Usage Data</h4>
                <p>Usage Data is collected automatically when using the Service.</p>
                <p>Usage Data may include information such as Your Device"s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            </div>
            <div>
                <h4>Information from Third-Party Social Media Services</h4>
                <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
                <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
            </div>
            <div>
                <h4>Retention of Your Personal Data</h4>
                <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
            </div>
            <div>
                <h4>Business Transactions</h4>
                <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
            </div>
            <div>
                <h4>Law enforcement</h4>
                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            </div>
            <div>
                <h4>Children's Privacy</h4>
                <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
            </div>
            <div>
                <h4>Links to Other Websites</h4>
                <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
            </div>
            <div>
                <h4>Changes to this Privacy Policy</h4>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
                <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
            </div>
            <div>
                <h4>Contact Us</h4>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <p>By visiting this page on our website: <Link href={'/contactus'}>http://E-Commerce.com/contact</Link></p>
            </div>
        </div>
    </>
  )
}

export default Privacy